F23-CS-407/hubit

backend/Dockerfile
backend/README.md
backend/package-lock.json
backend/package.json
backend/src/app.js
backend/src/authentication/endpoints.js
backend/src/index.js
backend/tests/integration/authentication/endpoints.test.js
backend/tests/integration/index.test.js
backend/tests/unit/authentication/schemas.test.js
backend/tests/unit/authentication/utils.test.js
backend/tests/unit/index.test.js
compose.yaml
database/README.md

Uses an in memory mongo instance as a test database that gets cleared between each test

Backend Testing Framework / Auth tests

---

backend/README.md
backend/src/authentication/endpoints.js
backend/src/authentication/index.js
backend/src/authentication/utils.js
backend/tests/integration/authentication/endpoints.test.js
backend/tests/unit/authentication/utils.test.js

Delete user endpoint and tests

delete user endpoint

---

backend/src/app.js
backend/src/authentication/index.js
backend/src/debug/test-app.js
backend/tests/integration/authentication/cookies.test.js

Default cookie expiry is 1 day, cookieMaxAge can be passed through options to createApp() to change this behavior

expire cookies

---

backend/src/app.js
backend/src/communities/endpoints.js
backend/src/communities/index.js
backend/src/communities/schemas.js
backend/tests/integration/communities/endpoints.test.js

Basic backend features for community creation, searching by community name, searching for users by username, and searching for one specific user by username.

Basic-community-features

---

backend/src/communities/endpoints.js
backend/src/communities/index.js
backend/src/communities/posts/comments/endpoints.js
backend/src/communities/posts/comments/schemas.js
backend/src/communities/posts/endpoints.js
backend/src/communities/posts/schemas.js
backend/src/communities/schemas.js
backend/tests/integration/communities/posts/comments/endpoints.test.js
backend/tests/integration/communities/posts/endpoints.test.js

Backend calls for creating posts, likes, and comments, retrieving posts from communities, retrieving comments and likes from posts, deleting likes, and additionally determining whether a user has liked a post.

Merge post features into main

---

frontend/src/app/app-routing.module.ts
frontend/src/app/app.component.html
frontend/src/app/app.module.ts
frontend/src/app/permadelete/Account Editing.md
frontend/src/app/permadelete/permadelete.component.html
frontend/src/app/permadelete/permadelete.component.spec.ts
frontend/src/app/permadelete/permadelete.component.ts
frontend/src/app/profile/profile.component.html
frontend/src/app/profile/profile.component.ts
frontend/src/app/signup/.env.txt
frontend/src/app/signup/signup.component.html
frontend/src/app/signup/signup.component.ts
frontend/test/Account Editing.md
frontend/test/authentication with keyboard.txt
h

When you get to the sign up page, there will be duplicate create password/re-enter password fields. I'm curious how they look in comparison

More Accessible Alternative to Form creation, though could be implemented into the already given input classes

---

backend/src/authentication/endpoints.js
backend/src/communities/endpoints.js
backend/src/communities/index.js
backend/src/communities/posts/comments/endpoints.js
backend/src/communities/posts/comments/schemas.js
backend/src/communities/posts/endpoints.js
backend/src/communities/posts/schemas.js
backend/src/communities/schemas.js
backend/tests/integration/communities/endpoints.test.js
backend/tests/integration/communities/posts/comments/endpoints.test.js
backend/tests/integration/communities/posts/endpoints.test.js

Prettier also ran so it's much smaller diff than it appears

All responses are in json

---

backend/src/app.js
backend/src/authentication/schemas.js
backend/src/communities/posts/endpoints.js
backend/src/user/endpoints.js
backend/src/user/index.js

update user info

---

backend/src/communities/endpoints.js
backend/src/communities/index.js

basic functionality

---

backend/README.md
backend/src/communities/posts/endpoints.js

Endpoint Documentation

---

backend/README.md
backend/src/communities/endpoints.js
backend/src/communities/index.js
backend/src/communities/posts/comments/endpoints.js
backend/src/communities/posts/endpoints.js
backend/src/user/endpoints.js
backend/src/user/index.js
backend/tests/integration/communities/endpoints.test.js
backend/tests/integration/communities/posts/comments/endpoints.test.js
backend/tests/integration/communities/posts/endpoints.test.js
backend/tests/integration/user/endpoints.test.js

GET /user?id=(string)
GET /community?id=(string)
GET /post?id=(string)
GET /comment?id=(string)
Additional tests for /change_username, /change_password
Removed previous get user endpoint to place it under user directory

Get endpoints

---

backend/src/authentication/endpoints.js
backend/src/authentication/schemas.js
backend/src/user/endpoints.js
backend/tests/integration/authentication/endpoints.test.js
backend/tests/integration/user/endpoints.test.js
backend/tests/unit/authentication/schemas.test.js

Adds 2 methods to User objects
scrub(): removes personal information, for now just salt and password_hash
deleteResursive(): delete this user and all children, in the future will delete posts and remove as mod from communities, etc

scrub method

---

backend/package-lock.json
backend/package.json
compose.yaml

For frontend and backend. Changes made to files while an image is running will be reflected in that running image. So no need to stop and rebuild to test through docker. Running with the proxy should be much easier while developing (you will still need to refresh to see these changes).

changes update live through docker

---

backend/README.md
backend/src/authentication/schemas.js
backend/src/authentication/utils.js
backend/src/communities/endpoints.js
backend/src/communities/index.js
backend/src/communities/posts/comments/endpoints.js
backend/src/communities/posts/comments/schemas.js
backend/src/communities/posts/endpoints.js
backend/src/communities/posts/schemas.js
backend/src/communities/schemas.js
backend/tests/integration/authentication/endpoints.test.js
backend/tests/integration/communities/endpoints.test.js
backend/tests/integration/communities/posts/comments/endpoints.test.js
backend/tests/integration/communities/posts/endpoints.test.js

Instead of calling delete() to destroy an object, each object should have a delete procedure called deleteRecursive() that takes care of side effects. For example, deleting a comment deletes all child comments, removes from user's comment list, and removes from parent's comment list.
Depends on https://github.com/F23-CS-407/hubit/pull/35
Added DELETE /comment
Added DELETE /post
Added DELETE /community
User object added mod_for list. If community is created with User as mod then community is added to this list. If User is deleted then they will be removed from the mod lists of the communities in their mod_for list. If removing user from mod list results in 0 mods the community and all child content will be deleted.
User object added comments list. If user makes comment, it is added to this …

Bidirectional references and recursive deletion behavior

---

backend/package.json
compose.yaml

Fixes an issue where mounted node_modules overwrites built node_modules

keep host node_modules out of mount scope

---

backend/README.md
backend/src/user/endpoints.js
backend/src/user/index.js
backend/tests/integration/user/endpoints.test.js

Added POST /change_password. Should be last of the update user information page endpoints.

change password

---

frontend/src/app/app.component.css
frontend/src/app/app.component.html
frontend/src/app/app.module.ts
frontend/src/app/comment/comment.component.css
frontend/src/app/comment/comment.component.html
frontend/src/app/comment/comment.component.spec.ts
frontend/src/app/comment/comment.component.ts
frontend/src/app/home/home.component.html
frontend/src/app/new-community/new-community.component.ts
frontend/src/app/post/post.component.css
frontend/src/app/post/post.component.html
frontend/src/app/post/post.component.ts
frontend/src/app/profile/profile.component.css
frontend/src/app/profile/profile.component.ts
frontend/src/models/Comment.ts

Go to a post's page to comment.
See post's previous comments.
Delete your comment with delete button.
Fixed search bar routing.
- Prior Issue: Users linked to community page, and community page to profile.

Post Comments

---

frontend/src/app/account_data/account_data.component.html
frontend/src/app/account_data/account_data.component.ts
frontend/src/app/app.module.ts
frontend/src/app/community/community.component.css
frontend/src/app/direct-message/direct-message.component.css
frontend/src/app/direct-message/direct-message.component.html
frontend/src/app/direct-message/direct-message.component.spec.ts
frontend/src/app/direct-message/direct-message.component.ts
frontend/src/app/file-upload.service.spec.ts
frontend/src/app/file-upload.service.ts
frontend/src/app/new-community/new-community.component.html
frontend/src/app/new-community/new-community.component.ts
frontend/src/app/new_post/new_post.component.css
frontend/src/app/new_post/new_post.component.html
frontend/src/app/new_post/new_post.component.ts
frontend/src/app/profile/profile.component.css
frontend/src/app/profile/profile.component.html
frontend/src/app/profile/profile.component.ts

Image Selection on Post, Profile, and new DM page.

Image & DM

---

frontend/angular.json
frontend/package-lock.json
frontend/package.json
frontend/src/app/app.module.ts
frontend/src/app/new_post/new_post.component.ts
frontend/src/app/post/post.component.css
frontend/src/app/post/post.component.html
frontend/src/app/post/post.component.ts
frontend/src/app/profile/profile.component.css
frontend/src/app/profile/profile.component.html
frontend/src/app/profile/profile.component.ts
frontend/tsconfig.json

Posts can be embedded (does not show comments and directs to /post page on click)
Posts can show image and video media

Post media viewing, embedded posts

---

frontend/Dockerfile
frontend/src/app/account_data/account_data.component.ts
frontend/src/app/app.component.ts
frontend/src/app/community/community.component.ts
frontend/src/app/followed-communities/followed-communities.component.ts
frontend/src/app/home/home.component.ts
frontend/src/app/login/login.component.ts
frontend/src/app/new-community/new-community.component.ts
frontend/src/app/new_post/new_post.component.ts
frontend/src/app/permadelete/permadelete.component.ts
frontend/src/app/profile/profile.component.ts
frontend/src/app/signup/signup.component.ts
frontend/src/models/User.ts

No FE localhost references

---

backend/README.md
backend/src/app.js
backend/src/messages/endpoints.js
backend/src/messages/index.js
backend/src/messages/schemas.js

Fiinished commit

---

backend/README.md
backend/src/communities/index.js
backend/src/communities/posts/endpoints.js
backend/src/communities/posts/schemas.js

Post category backend support based on user story 8 requirements, with included endpoint.
Endpoint for getting all posts liked by a user for a given user ID.

Likes and categorization backend endpoints
